### PR TITLE
Add CP2K support for dpgen2

### PR DESCRIPTION
**Pull request by Cloudac7**
As described in #180 , dpgen2 did not support CP2K. 
This PR add `RunCp2k` and is tested to be OK to generate fp tasks.

Thus solved #180.

## Summary by CodeRabbit

- **New Features**
  - Introduced CP2K support with new classes for preparing and running CP2K tasks.
  - Added functionality for generating CP2K input files from user configurations.
  - Included new test cases for CP2K input generation and task execution.

- **Bug Fixes**
  - None

- **Documentation**
  - None

- **Refactor**
  - None

- **Style**
  - None

- **Tests**
  - Added test cases for `Cp2kInputs` and `RunCp2k` classes.

- **Chores**
  - None

- **Revert**
  - None

### CODE REVIEW

**Review by wanghan-iapcm — CHANGES_REQUESTED** [review]
I would recommend supporting the fp method cp2k in [fpop](https://github.com/deepmodeling/fpop) and wrap the operators like [what @zjgemi  does for abacus ](https://github.com/deepmodeling/fpop)

**Comment by Andy6M** [comment]
It seems that only the three elements C, N, and H and the corresponding pseudopotentials are considered in the code, and once there are other elements in the system, the code may be incorrect.

**Comment by Cloudac7** [comment]
> It seems that only the three elements C, N, and H and the corresponding pseudopotentials are considered in the code, and once there are other elements in the system, the code may be incorrect.

No, it is just a default dict as placeholder.

**Comment by Andy6M** [comment]
Hi @Cloudac7 :

Could you please provide the following example files:

An example of the CP2K inp file.
A corresponding input.json file for dpgen2.

These example files would be incredibly helpful for us to quickly get started and verify the new functionality.

Thank you very much!

**Comment by zjgemi** [comment]
https://github.com/deepmodeling/dpgen2/pull/238

**Comment by zjgemi** [comment]
https://github.com/deepmodeling/dpgen2/pull/238
CP2K support is implemented with FPOP. Please feed back if there is any question. I will close this PR.

**Pull request closed without merging**
